export interface SurahData {
  id: string;
  surah_number: number;
  arabic_name: string;
  english_name: string;
  revelation_type: 'meccan' | 'medinan';
  core_theme: string;
  structural_axis: string;
  sufi_reflection: string;
  interfaith_resonance: string | null;
  has_interfaith_note: boolean;
}

export const SURAH_COMMENTARY: SurahData[] = [
  {
    id: '6fb3d8e5-0c1e-4936-983b-419ff54e3146',
    surah_number: 1,
    arabic_name: 'Al-Fatiha',
    english_name: 'The Opening',
    revelation_type: 'meccan',
    core_theme: 'Orientation toward Divine Sovereignty.',
    structural_axis: 'Dependence and Guidance',
    sufi_reflection: 'Al-Fatiha establishes the metaphysical posture of the seeker: recognition of Divine Lordship, confession of dependence, and request for straight alignment. The path is not self-constructed; it is sought. Guidance is relational, not abstract. Every prayer begins here — not as ritual formality but as ontological orientation.',
    interfaith_resonance: 'Parallels covenantal prayer structures found in the Psalms. The threefold movement of praise, confession, and petition echoes the Amidah.',
    has_interfaith_note: true,
  },
  {
    id: 'bfae9d2c-4bcd-4380-b1e1-9a89cd2e8fa9',
    surah_number: 2,
    arabic_name: 'Al-Baqarah',
    english_name: 'The Cow',
    revelation_type: 'medinan',
    core_theme: 'Covenant, Law, and Community Formation.',
    structural_axis: 'Obedience as Stabilization',
    sufi_reflection: "This Surah constructs civilizational scaffolding. It demonstrates that spiritual aspiration without structure dissolves. Law disciplines desire. Community refines the ego. The longest chapter of the Qur'an because the task of ordering human life in light of divine reality requires the most sustained engagement.",
    interfaith_resonance: "Extensive engagement with Mosaic covenant narrative; the longest interfaith address in the Qur'an.",
    has_interfaith_note: true,
  },
  {
    id: '44cbaa41-c841-43d3-87eb-bf707ba4add5',
    surah_number: 3,
    arabic_name: 'Aal-Imran',
    english_name: 'Family of Imran',
    revelation_type: 'medinan',
    core_theme: 'Continuity of Revelation across the prophetic chain.',
    structural_axis: 'Prophetic Lineage',
    sufi_reflection: 'This Surah situates Muhammad within Abrahamic continuity. Revelation unfolds across history without negating prior disclosure. Difference reflects unfolding context, not rupture of source. The prophetic family of Imran — encompassing Mary and Jesus — is honored within an Islamic metaphysical framework.',
    interfaith_resonance: 'Direct engagement with Christian theological claims; affirmation of Jesus as Word of God (Kalimah) within Islamic context.',
    has_interfaith_note: true,
  },
  {
    id: '8ec49d2b-8523-4cd4-83fa-f5e834903cf1',
    surah_number: 4,
    arabic_name: 'An-Nisa',
    english_name: 'The Women',
    revelation_type: 'medinan',
    core_theme: 'Justice and Social Responsibility as expressions of faith.',
    structural_axis: 'Protection of the Vulnerable',
    sufi_reflection: 'Justice is not abstract virtue; it is protection of trust. Spirituality that neglects social order is incomplete. The divine command to protect women, orphans, and the weak grounds metaphysical aspiration in material obligation. Accountability before God includes accountability within human community.',
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '1e2b41dd-ca35-486d-b454-9650a7f45fbc',
    surah_number: 5,
    arabic_name: "Al-Ma'idah",
    english_name: 'The Table Spread',
    revelation_type: 'medinan',
    core_theme: 'Covenantal Responsibility and Final Clarification of Divine Law.',
    structural_axis: 'Fulfillment',
    sufi_reflection: 'This Surah emphasizes completion of moral law and integrity in covenant. Fulfillment is not innovation; it is stabilization. The table spread from heaven signals that divine provision is complete. What remains is human fidelity to what has been given, not the seeking of additions.',
    interfaith_resonance: 'Direct address to People of the Book; engagement with both Torah and Gospel communities.',
    has_interfaith_note: true,
  },
  {
    id: '55f4c69c-edd7-4b50-b3ac-bb7b2663c6bb',
    surah_number: 6,
    arabic_name: "Al-An'am",
    english_name: 'The Cattle',
    revelation_type: 'meccan',
    core_theme: 'Divine sovereignty over creation and the folly of associating partners with God.',
    structural_axis: 'Divine Unity',
    sufi_reflection: 'This Surah dismantles polytheism through argument, not force. The natural world — cattle, stars, seeds — is a continuous theophany. One who perceives with clarity cannot distribute sovereignty across multiple divine agencies. Tawhid is not a theological proposition; it is the direct reading of reality.',
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'cfab4ad0-7228-4330-b893-05fb6bbc80bf',
    surah_number: 7,
    arabic_name: "Al-A'raf",
    english_name: 'The Heights',
    revelation_type: 'meccan',
    core_theme: 'The human condition between elevation and descent, Paradise and Fire.',
    structural_axis: 'Moral Accountability',
    sufi_reflection: "Al-A'raf describes the ridge between states — a metaphysical threshold. The Surah traces human history from Adam's fall to the missions of multiple prophets, showing the recurring pattern: divine offer, human refusal, consequence. The inner life mirrors this drama constantly.",
    interfaith_resonance: 'Parallel to the Hebrew narrative of Exodus and prophetic history.',
    has_interfaith_note: true,
  },
  {
    id: '1ea72795-174d-4126-bcc5-2d59052adb47',
    surah_number: 8,
    arabic_name: 'Al-Anfal',
    english_name: 'The Spoils of War',
    revelation_type: 'medinan',
    core_theme: 'The ethics of conflict and the primacy of Divine will over human calculation.',
    structural_axis: 'Surrender to Divine Order',
    sufi_reflection: 'This Surah reveals that victory is not a product of military excellence but of alignment with divine will. The battle of Badr becomes a metaphysical teaching: when human effort reaches its limit, unseen support arrives. Tawakkul — complete reliance on God — is not passivity but the completion of responsible action.',
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'a74e9efc-0ee2-476a-a3ed-0ae8946df79b',
    surah_number: 9,
    arabic_name: 'At-Tawbah',
    english_name: 'The Repentance',
    revelation_type: 'medinan',
    core_theme: 'Accountability, repentance, and the boundaries of covenantal community.',
    structural_axis: 'Accountability',
    sufi_reflection: "The only Surah without an opening Bismillah — traditionally interpreted as signaling severity of its message. Accountability is here structural, not merely personal. Communities that breach covenant face consequence. Repentance, however, is always available to the sincere. The door of return is never permanently closed.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'ca18b239-61c8-48ae-8671-77bd1ca6826a',
    surah_number: 10,
    arabic_name: 'Yunus',
    english_name: 'Jonah',
    revelation_type: 'meccan',
    core_theme: 'Patience with divine timing and the universality of prophetic invitation.',
    structural_axis: 'Trust in Divine Timing',
    sufi_reflection: "Jonah's story is told briefly here to illuminate a principle: divine mercy extends even to those who initially reject it. The people of Nineveh believed and were spared — an anomaly in prophetic narrative that reveals the depth of divine compassion. Patience is not resignation; it is synchronized movement with divine unfolding.",
    interfaith_resonance: 'Jonah narrative shared across Jewish, Christian, and Islamic tradition.',
    has_interfaith_note: true,
  },
  {
    id: '7add4367-41e5-48a2-9862-7f8f15a9c944',
    surah_number: 11,
    arabic_name: 'Hud',
    english_name: 'Hud',
    revelation_type: 'meccan',
    core_theme: 'The stories of prophets as mirrors of the perennial human encounter with divine command.',
    structural_axis: 'Prophetic Warning',
    sufi_reflection: 'This Surah is said to have aged the Prophet — not from fear but from the weight of its message. Multiple prophetic stories compress into a single revelation: the pattern of invitation, denial, and consequence is constant. History teaches the soul what argument alone cannot. Recognition of pattern is itself a form of wisdom.',
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'f58d52f5-e25b-45ea-99f0-b09d53ebfcd4',
    surah_number: 12,
    arabic_name: 'Yusuf',
    english_name: 'Joseph',
    revelation_type: 'meccan',
    core_theme: 'Divine providence operating through apparent adversity toward ultimate elevation.',
    structural_axis: 'Divine Providence',
    sufi_reflection: "The most complete narrative in the Qur'an. Yusuf's story is the anatomy of a soul's journey: trial, patience, betrayal, imprisonment, and eventual elevation. The Sufi reads this as an inner map. Every descent is purposeful. Every separation is preparation. The reunion at the end is not merely filial — it is ontological.",
    interfaith_resonance: 'Joseph narrative shared across all three Abrahamic traditions; uniquely complete in Quranic presentation.',
    has_interfaith_note: true,
  },
  {
    id: 'ee384299-dfa8-43e7-ab57-c69d8c3f8d0a',
    surah_number: 13,
    arabic_name: "Ar-Ra'd",
    english_name: 'The Thunder',
    revelation_type: 'medinan',
    core_theme: 'Divine power manifested in natural phenomena and the establishment of divine law.',
    structural_axis: 'Divine Majesty',
    sufi_reflection: 'Thunder declares the glory of God. The Surah situates natural phenomena as continuous glorification. Nothing in the cosmos is mute — everything speaks the divine reality to those with ears attuned. The seeker learns to read the book of creation alongside the book of revelation.',
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '711eec6e-f93d-4ff8-bd73-213329be9a72',
    surah_number: 14,
    arabic_name: 'Ibrahim',
    english_name: 'Abraham',
    revelation_type: 'meccan',
    core_theme: "Gratitude, covenant, and the primordial prayer of Abraham for the community of believers.",
    structural_axis: 'Gratitude and Covenant',
    sufi_reflection: "Abraham's prayer for his descendants and for the city of Mecca is the Surah's axis. Gratitude here is not sentiment but structural recognition: all provision originates in divine generosity. The human task is acknowledgment, not possession.",
    interfaith_resonance: "Abraham as shared patriarch; his prayer for progeny resonates with Torah's covenant narrative.",
    has_interfaith_note: true,
  },
  {
    id: '14627509-5798-4ae5-a00b-611399e06d33',
    surah_number: 15,
    arabic_name: 'Al-Hijr',
    english_name: 'The Rocky Tract',
    revelation_type: 'meccan',
    core_theme: 'Divine protection of revelation and the dignity of the human soul.',
    structural_axis: 'Divine Protection',
    sufi_reflection: "God declares that He has revealed the Remembrance and will protect it. This is not merely textual preservation — it is the inviolability of divine guidance against human distortion. The Surah also contains the creation of Adam and the refusal of Iblis, reminding the reader that the soul's elevation is matched by the persistence of the ego's resistance.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'dcc62b6d-45df-4368-99ad-dabc1023a65a',
    surah_number: 16,
    arabic_name: 'An-Nahl',
    english_name: 'The Bee',
    revelation_type: 'meccan',
    core_theme: 'Signs in creation pointing to divine wisdom and the comprehensive nature of divine blessing.',
    structural_axis: 'Divine Wisdom in Nature',
    sufi_reflection: 'The bee receives divine inspiration and produces honey — healing and sweetness emerging from precise obedience to natural law. This is a Sufi emblem: the practitioner who follows the guidance of the teacher and the path produces, from ordinary life, something that nourishes others. Obedience is not restriction; it is optimization.',
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '1924ba3f-646e-49b4-9b5e-5aa2b365bcde',
    surah_number: 17,
    arabic_name: 'Al-Isra',
    english_name: 'The Night Journey',
    revelation_type: 'meccan',
    core_theme: 'The spiritual ascent and the comprehensive moral architecture of the prophetic mission.',
    structural_axis: 'Spiritual Ascent',
    sufi_reflection: "The night journey of the Prophet — from Mecca to Jerusalem to the Divine Presence — is the Surah's opening and governing metaphor. The Sufi reads this as the soul's capacity for ascent beyond ordinary perception. The seventeen obligatory prayers are instituted during this journey, embedding ascent into the daily rhythmic structure of the practitioner's life.",
    interfaith_resonance: 'Jerusalem as shared sacred geography for Judaism, Christianity, and Islam.',
    has_interfaith_note: true,
  },
  {
    id: '81f43541-7216-4bc4-81fe-3a7f637c1450',
    surah_number: 18,
    arabic_name: 'Al-Kahf',
    english_name: 'The Cave',
    revelation_type: 'meccan',
    core_theme: 'Protection, knowledge, and the encounter between human limitation and divine wisdom.',
    structural_axis: 'Knowledge and Humility',
    sufi_reflection: "The cave offers protection from corrupt social environment — withdrawal in service of preservation. The story of Khidr and Moses is the Surah's philosophical heart: Moses, despite prophetic rank, cannot comprehend the actions of the divine emissary. Humility before superior knowledge is not defeat; it is the precondition of deeper learning.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '609374ba-3737-4565-9778-c8e8592efba2',
    surah_number: 19,
    arabic_name: 'Maryam',
    english_name: 'Mary',
    revelation_type: 'meccan',
    core_theme: 'Divine miracle, prophetic lineage, and the honor accorded to devoted servants of God.',
    structural_axis: 'Miraculous Provision',
    sufi_reflection: "Mary is the only woman named in the Qur'an and receives her own Surah — a significant theological affirmation. The divine provision that comes to her, unsought, while in seclusion, models a principle: sincere withdrawal in devotion creates the conditions for divine visitation. The miraculous is not arbitrary; it is responsive.",
    interfaith_resonance: 'Direct engagement with the Marian tradition of Christianity; extended address to Christian theological understanding.',
    has_interfaith_note: true,
  },
  {
    id: 'cf698c8c-2b98-4643-b521-5001e6bf84f3',
    surah_number: 20,
    arabic_name: 'Ta Ha',
    english_name: 'Ta Ha',
    revelation_type: 'meccan',
    core_theme: 'Moses as exemplar of the soul in direct encounter with divine command.',
    structural_axis: 'Divine Command and Human Response',
    sufi_reflection: 'The encounter at the burning bush — remove your sandals, you are in holy ground — is read by the Sufi as the stripping away of ordinary selfhood before the divine presence. Moses is sent not because he is perfect but because he is responsive. Prophetic selection is not about credentials; it is about openness to the call.',
    interfaith_resonance: 'The Moses narrative — burning bush, exodus, covenant — is foundational to all Abrahamic traditions.',
    has_interfaith_note: true,
  },
  {
    id: 'e92fc4d1-4393-4c91-b165-d599e8b2c31f',
    surah_number: 21,
    arabic_name: 'Al-Anbiya',
    english_name: 'The Prophets',
    revelation_type: 'meccan',
    core_theme: 'The unity of the prophetic mission across all messengers.',
    structural_axis: 'Prophetic Unity',
    sufi_reflection: 'This Surah enumerates prophets in rapid succession — Ibrahim, Lut, Nuh, Dawud, Sulaiman, Ayyub, Yunus, Zakariyya, Yahya, Isa — revealing the single current flowing through diverse human vessels. The message is structurally identical across all prophets; the context and emphasis shift with historical need. Unity of source, diversity of expression.',
    interfaith_resonance: 'Prophets shared across traditions: Noah, Abraham, David, Solomon, Elijah, Jonah, Zechariah, John, Jesus.',
    has_interfaith_note: true,
  },
  {
    id: '1f92896b-a24e-47e0-8691-6f9cbbe85c77',
    surah_number: 22,
    arabic_name: 'Al-Hajj',
    english_name: 'The Pilgrimage',
    revelation_type: 'medinan',
    core_theme: "The cosmic significance of pilgrimage and the annihilation of the self in divine remembrance.",
    structural_axis: 'Sacred Ritual and Cosmic Order',
    sufi_reflection: "Hajj is the outer form of an inner journey: the compression of the soul's entire existential drama into a few days of circumambulation, running, standing, and sacrifice. The Sufi sees in the rites of pilgrimage the complete itinerary of the inner path — departure from ordinary life, arrival at the center, circumambulation of the Real, return transformed.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '57923bed-21d5-482f-9b2f-49f09b0006c9',
    surah_number: 23,
    arabic_name: "Al-Mu'minun",
    english_name: 'The Believers',
    revelation_type: 'meccan',
    core_theme: 'The qualities of the true believer as markers of genuine inner development.',
    structural_axis: 'Qualitative Faith',
    sufi_reflection: 'The Surah opens with a precise inventory of the believer\'s character: humility in prayer, avoidance of vain speech, performance of purification, guardianship of trusts and covenants. These are not performance criteria; they are diagnostic indicators of genuine inner transformation. Belief that does not alter conduct is not yet belief — it is information.',
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'db44ebdd-14c1-4e51-abec-fa3e5873c8c8',
    surah_number: 24,
    arabic_name: 'An-Nur',
    english_name: 'The Light',
    revelation_type: 'medinan',
    core_theme: 'Divine Light as the governing metaphysical reality and the ethics of communal purity.',
    structural_axis: 'Divine Light',
    sufi_reflection: "The famous Light Verse — God is the Light of the heavens and earth — is the Sufi's touchstone. Light does not exist alongside darkness; it displaces it. The divine reality is not one reality among others; it is the condition for all other realities to be visible at all. All that is seen is seen by the Light that is God.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '38ce8283-31a7-4fa6-9b27-e2ffa5b262dc',
    surah_number: 25,
    arabic_name: 'Al-Furqan',
    english_name: 'The Criterion',
    revelation_type: 'meccan',
    core_theme: "The Qur'an as the criterion between truth and falsehood, guidance and deviation.",
    structural_axis: 'Discernment',
    sufi_reflection: "Furqan is one of the Qur'an's self-designations: the Criterion, the separator of truth from falsehood. The Sufi's task is to develop an inner furqan — a faculty of discernment refined through practice and guidance that distinguishes the promptings of the Real from the elaborations of the ego. External criterion and internal criterion develop together.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '0c36a8c1-c7ee-4927-9f87-21e2ab433376',
    surah_number: 26,
    arabic_name: "Ash-Shu'ara",
    english_name: 'The Poets',
    revelation_type: 'meccan',
    core_theme: 'The contrast between true prophecy and mere eloquence, divine speech and human performance.',
    structural_axis: 'Authenticity of Transmission',
    sufi_reflection: 'The Surah distinguishes prophets from poets: prophets speak what they receive; poets speak what they fabricate. The ego is a poet — endlessly creative, endlessly self-referential. The prophetic soul is a transmitter: its speech carries weight precisely because it originates elsewhere. The spiritual path cultivates this quality of receptive transmission.',
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '6d91a591-6c90-47c3-9dbb-700a884d2593',
    surah_number: 27,
    arabic_name: 'An-Naml',
    english_name: 'The Ant',
    revelation_type: 'meccan',
    core_theme: 'Divine knowledge encompassing all creatures and the sovereignty of God over all realms.',
    structural_axis: 'Omniscience',
    sufi_reflection: "Even the ant, in its subterranean community, is within the field of divine awareness. Solomon hears the ant's speech. The Sufi principle here: nothing is too small for divine attention; no creature is outside the field of divine provision. The seeker who feels overlooked by the divine has simply not yet perceived the attention that is already present.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '55d29984-b9ad-47df-b124-5a876bd22a0d',
    surah_number: 28,
    arabic_name: 'Al-Qasas',
    english_name: 'The Stories',
    revelation_type: 'meccan',
    core_theme: 'The life of Moses as complete prophetic biography and metaphysical teaching.',
    structural_axis: 'Providential History',
    sufi_reflection: "Moses's story here spans from birth to prophethood — a complete arc of divine arrangement. The infant placed in a river, the palace that becomes a preparation ground, the exile that becomes purification, the return that becomes liberation. Nothing in this sequence was accidental. Providence does not operate through accident; it operates through apparent accident.",
    interfaith_resonance: 'Moses narrative as shared Abrahamic patrimony.',
    has_interfaith_note: true,
  },
  {
    id: '65fc59f3-3088-4906-b36a-e2bc16749f54',
    surah_number: 29,
    arabic_name: 'Al-Ankabut',
    english_name: 'The Spider',
    revelation_type: 'meccan',
    core_theme: 'Trial as the mechanism of genuine faith-formation and the fragility of false support.',
    structural_axis: 'Trial and Purification',
    sufi_reflection: "The spider's web is the Surah's governing metaphor: seemingly complex, apparently protective, but ultimately fragile. Supports built on other than the Real cannot bear the weight of existence. Trial is not punishment; it is the test of structural integrity. The soul that emerges from genuine trial does so with foundations that no spider's-web substitute can provide.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'f1c1a911-7dce-4526-8342-363f82cbf216',
    surah_number: 30,
    arabic_name: 'Ar-Rum',
    english_name: 'The Romans',
    revelation_type: 'meccan',
    core_theme: 'Divine governance over history and the cyclical patterns of civilizational rise and decline.',
    structural_axis: 'Historical Providential Order',
    sufi_reflection: 'This Surah opens with a historical prediction — the Romans will recover after defeat — and fulfillment came within the prophesied window. The Sufi lesson: divine knowledge encompasses historical movement that appears to human perception as chaos. The arc of civilizational history bends toward the divine purpose, even when human perception cannot trace the curve.',
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'cbde09e8-a0a6-49a8-b783-c22a24fd7fbd',
    surah_number: 31,
    arabic_name: 'Luqman',
    english_name: 'Luqman',
    revelation_type: 'meccan',
    core_theme: 'Wisdom as a divine gift and the transmission of guidance from father to child.',
    structural_axis: 'Transmission of Wisdom',
    sufi_reflection: "Luqman the wise counsels his son in a series of concise directives: do not associate partners with God, honor your parents, know that God sees the weight of a mustard seed, establish prayer, command good and forbid evil, do not walk with arrogance. This is a complete spiritual curriculum compressed into a father's testament. Wisdom is transmissible; it requires a receiver.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '963969d8-e204-4412-9cc9-008aa00addce',
    surah_number: 32,
    arabic_name: 'As-Sajdah',
    english_name: 'The Prostration',
    revelation_type: 'meccan',
    core_theme: 'The certainty of divine creation and the inevitability of return to the Divine.',
    structural_axis: 'Return to Origin',
    sufi_reflection: 'Prostration is the body\'s enactment of the soul\'s deepest truth: the creature before the Creator, the contingent before the Necessary, the derived before the Source. This Surah affirms that all created things will return — not as punishment but as the natural completion of a cycle initiated by divine origination.',
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '07034d3d-67d0-4bb0-82a3-7b8a7459dc98',
    surah_number: 33,
    arabic_name: 'Al-Ahzab',
    english_name: 'The Combined Forces',
    revelation_type: 'medinan',
    core_theme: 'The prophetic household as model and the nature of prophetic finality.',
    structural_axis: 'Prophetic Model',
    sufi_reflection: 'This Surah establishes Muhammad as the seal of the prophets and the ideal human exemplar. The prophetic household becomes a model community — not a royal dynasty but a school of character. The Sufi tradition draws from this Surah the principle that transmission of the path requires embodied exemplars, not merely texts.',
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '2361b0f0-a1e6-4f7e-97e6-bf96892968e4',
    surah_number: 34,
    arabic_name: 'Saba',
    english_name: 'Sheba',
    revelation_type: 'meccan',
    core_theme: 'Gratitude and ingratitude as the two fundamental responses to divine blessing.',
    structural_axis: 'Gratitude vs. Ingratitude',
    sufi_reflection: "The people of Sheba received an extraordinary civilization and abundance — and chose ingratitude. The Sufi sees in their story a warning about spiritual gifts: capacities and insights bestowed upon the seeker that are taken for personal possession rather than held as trust will, through ingratitude, dissolve. All gifts are loans; gratitude is the proper recognition of this.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '3fdedda6-94b0-41bc-804e-a48efcc8a234',
    surah_number: 35,
    arabic_name: 'Fatir',
    english_name: 'The Originator',
    revelation_type: 'meccan',
    core_theme: 'God as the sole originator of all existence and the diversity of human response to divine call.',
    structural_axis: 'Divine Origination',
    sufi_reflection: 'God originates creation from nothing — not from pre-existing matter but from pure divine will. The Sufi principle: the Real is the only genuine agent in existence. All secondary causes are transparent to the one cause. To perceive only secondary causes is to mistake the fingers for the speaker. Origination is a divine attribute; creation is divine act.',
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '2cb79768-7ee5-49d0-b83f-6d95123b366d',
    surah_number: 36,
    arabic_name: 'Ya Sin',
    english_name: 'Ya Sin',
    revelation_type: 'meccan',
    core_theme: "The heart of the Qur'an — divine mercy, human mortality, and the resurrection of the dead.",
    structural_axis: 'Resurrection and Mercy',
    sufi_reflection: "Called \"the heart of the Qur'an,\" Ya Sin addresses mortality with compassion rather than threat. The dead earth revived by rain is the governing metaphor for resurrection — not as forensic judgment but as the restoration of life by the One who originated it. The Sufi holds this Surah as an emblem of divine mercy's primacy over divine wrath.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '1ad5080e-2647-43c1-be82-23a873bbef9a',
    surah_number: 37,
    arabic_name: 'As-Saffat',
    english_name: 'Those Ranged in Ranks',
    revelation_type: 'meccan',
    core_theme: 'The angelic hierarchy, the prophetic narratives, and the ultimate triumph of divine truth.',
    structural_axis: 'Cosmic Order',
    sufi_reflection: "The ranged ranks of angels is an image of cosmic order: the entire created realm oriented toward the divine, organized in service, free of the ego's disorder. The prophets — Abraham, Isaac, Moses, Elijah, Jonah — appear here as exemplars of willing alignment with divine purpose. Order is not imposed from without; in the realized being, it arises naturally.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'cbdfe2a2-7a9a-4e79-99c9-4a43c1d65553',
    surah_number: 38,
    arabic_name: 'Sad',
    english_name: 'The Letter Sad',
    revelation_type: 'meccan',
    core_theme: 'The trials of David, Solomon, and Job as exemplars of prophetic patience and return.',
    structural_axis: 'Trial and Return',
    sufi_reflection: "David's grief, Solomon's trial, Job's endurance — the Surah gathers three prophets whose paths ran through loss before arriving at restoration. The pattern is consistent: genuine elevation follows genuine descent. The Sufi sees in this sequence not divine indifference but divine pedagogy. The soul is made larger by what it is asked to carry.",
    interfaith_resonance: 'David and Solomon as shared prophetic figures across the Abrahamic traditions.',
    has_interfaith_note: true,
  },
  {
    id: 'f1ba370f-d4a8-4f8d-aafb-5b94fdb65e74',
    surah_number: 39,
    arabic_name: 'Az-Zumar',
    english_name: 'The Crowds',
    revelation_type: 'meccan',
    core_theme: 'Sincerity of worship and the ultimate gathering of all souls before the Divine.',
    structural_axis: 'Sincerity',
    sufi_reflection: "The Surah repeatedly invokes sincerity — worship God with sincere devotion. Sincerity is the quality that transforms outward form into genuine act. The Sufi principle: a hundred rituals without sincerity produce less than a single act of genuine presence before the Real. The crowd on the day of gathering is sorted not by the quantity of deeds but by their quality of orientation.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '26d57027-1309-408a-864c-790bd5b6bd8d',
    surah_number: 40,
    arabic_name: 'Ghafir',
    english_name: 'The Forgiver',
    revelation_type: 'meccan',
    core_theme: 'Divine forgiveness as a primary attribute and the inevitability of divine justice.',
    structural_axis: 'Divine Forgiveness',
    sufi_reflection: "One of the names of God in this Surah is Ghafir — the Forgiver of sin, Acceptor of repentance. The Sufi holds this as foundational: divine forgiveness is not the exception but the operating condition of the divine-human relationship. The seeker who understands this does not fear approaching the divine after failure — the door of return is always open to sincere return.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'dc8e46e6-473e-46c8-a1ed-46d4f32e14fd',
    surah_number: 41,
    arabic_name: 'Fussilat',
    english_name: 'Explained in Detail',
    revelation_type: 'meccan',
    core_theme: "The Qur'an as detailed explanation and the testimony of the human body on the Day of Judgment.",
    structural_axis: 'Divine Speech and Human Accountability',
    sufi_reflection: "This Surah declares that on the Day of Judgment, the human body itself will testify — hands, feet, and skin will speak. The Sufi reads this as a present reality: every action inscribes itself into the subtle body of the practitioner. Nothing is without trace. Spiritual development is partly the work of ensuring that what inscribes itself is worthy of its permanent mark.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '1fe2d406-43a8-4f02-869a-321c31eaa250',
    surah_number: 42,
    arabic_name: 'Ash-Shura',
    english_name: 'The Consultation',
    revelation_type: 'meccan',
    core_theme: 'Divine revelation as the highest mode of communication and the unity underlying apparent diversity.',
    structural_axis: 'Unity through Diversity',
    sufi_reflection: "The Surah affirms that what God has prescribed for this community is what He prescribed for Noah, Abraham, Moses, and Jesus — the same religion of surrender across all prophetic dispensations. The Sufi sees here confirmation that the inner path is not an Islamic novelty but the perennial current flowing beneath all authentic prophetic traditions.",
    interfaith_resonance: 'Explicit identification of the same essential religion across Noah, Abraham, Moses, Jesus, Muhammad.',
    has_interfaith_note: true,
  },
  {
    id: 'a138a876-7a48-4ce1-87be-6a8c0eded9b8',
    surah_number: 43,
    arabic_name: 'Az-Zukhruf',
    english_name: 'The Gold Adornments',
    revelation_type: 'meccan',
    core_theme: 'The deceptiveness of worldly adornment and the permanence of the divine word.',
    structural_axis: 'Non-Attachment',
    sufi_reflection: "Gold adorns — and distracts. The Surah challenges the seeker to examine what they have mistaken for the Real that is merely its ornament. Worldly beauty, status, comfort, and recognition are gold adornments on the surface of existence. The Sufi path is the progressive stripping away of these until the underlying reality is encountered without mediation.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'e9f66a38-6530-401e-9953-4b830134b455',
    surah_number: 44,
    arabic_name: 'Ad-Dukhan',
    english_name: 'The Smoke',
    revelation_type: 'meccan',
    core_theme: 'The signs of the hour and the consequences of rejecting clear divine guidance.',
    structural_axis: 'Consequence of Rejection',
    sufi_reflection: "The smoke that will appear as a sign of the approaching hour is an image of obscuration — the covering of clear perception that results from accumulated denial. The Sufi applies this inwardly: the ego's successive denials of the Real produce a progressive darkening of inner vision. Clarity is not a given; it must be maintained through continuous alignment.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '42ba3b27-8f15-46bc-8584-8551ee202cde',
    surah_number: 45,
    arabic_name: 'Al-Jathiyah',
    english_name: 'The Kneeling',
    revelation_type: 'meccan',
    core_theme: 'The signs of divine power in creation and the final kneeling of all communities before God.',
    structural_axis: 'Universal Accountability',
    sufi_reflection: "All communities will kneel — not as defeat but as the final recognition that sovereignty belongs to the Real alone. The Sufi sees this as the destination of the inner journey: the complete dissolution of the illusion of independent selfhood before the divine reality. Every genuine spiritual practice is a rehearsal for this ultimate kneeling.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '841115d1-07e1-4650-b568-45ea4ab43738',
    surah_number: 46,
    arabic_name: 'Al-Ahqaf',
    english_name: 'The Curved Sand Dunes',
    revelation_type: 'meccan',
    core_theme: 'Prophetic patience in the face of rejection and the mercy extended to sincere seekers.',
    structural_axis: 'Patience and Mercy',
    sufi_reflection: "The Surah narrates a group of jinn who heard the Qur'an recited, believed, and returned to their community as teachers. The message: sincere receptivity to divine guidance does not require prior religious credentials. The divine call is not restricted to those who already stand within institutional structures. Whoever hears and responds with sincerity has arrived.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '6d729a0a-e757-48f8-ada0-5dda8c16bb08',
    surah_number: 47,
    arabic_name: 'Muhammad',
    english_name: 'Muhammad',
    revelation_type: 'medinan',
    core_theme: "The divine support for the prophetic mission and the qualities of the sincere believer.",
    structural_axis: 'Prophetic Mission',
    sufi_reflection: "This Surah bears the Prophet's name and affirms divine support for his mission — not unconditional military victory but alignment with divine purpose. The Sufi principle: when human effort and divine will are aligned, the outcome is not always what was expected but is always what was required. Alignment is the practitioner's responsibility; outcomes belong to the Real.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'f51c1b08-e8ee-42ab-b536-7d6003eba6d4',
    surah_number: 48,
    arabic_name: 'Al-Fath',
    english_name: 'The Victory',
    revelation_type: 'medinan',
    core_theme: 'Manifest victory as divine gift and the expansion of divine light through the prophetic mission.',
    structural_axis: 'Divine Victory',
    sufi_reflection: "The Treaty of Hudaybiyya, apparently a political compromise, is called by God a manifest victory. This reframing is the Surah's essential teaching: what appears as loss or limitation from the human vantage point may be precisely what divine wisdom required. The practitioner who trusts the divine assessment over their own is on the path of genuine surrender.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'b99bcf89-1a21-483a-ac4a-39459922f485',
    surah_number: 49,
    arabic_name: 'Al-Hujurat',
    english_name: 'The Private Apartments',
    revelation_type: 'medinan',
    core_theme: "The ethics of community, respect, and the highest form of nobility before God.",
    structural_axis: 'Community Ethics',
    sufi_reflection: "The Surah establishes a complete ethics of interpersonal conduct: do not raise your voices above the Prophet's, verify news before acting, do not mock, do not defame, do not spy, do not backbite. The most noble before God is the most deeply conscious of God. The Sufi sees in this Surah that inner development without relational refinement is incomplete development.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'e8954c21-386f-4bd6-ba58-55559a2efaba',
    surah_number: 50,
    arabic_name: 'Qaf',
    english_name: 'The Letter Qaf',
    revelation_type: 'meccan',
    core_theme: "The certainty of resurrection and God's complete awareness of every thought and movement.",
    structural_axis: 'Divine Omniscience',
    sufi_reflection: "We are closer to the human being than the jugular vein. This verse, which the Sufi tradition has taken as its most intimate statement of divine proximity, appears here. The divine is not distant and judgmental but present and intimate. The interior life is not a private space; it is a continuously witnessed reality. This awareness is the foundation of sincere practice.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'd61c884a-2e1f-4f82-a943-08f3cb261edf',
    surah_number: 51,
    arabic_name: 'Adh-Dhariyat',
    english_name: 'The Winds that Scatter',
    revelation_type: 'meccan',
    core_theme: 'Creation as divine testimony and the primordial covenant of divine service.',
    structural_axis: 'Purpose of Creation',
    sufi_reflection: 'I have not created jinn and humans except to worship Me. This is the Surah\'s distillation: existence has a telos, a purpose inscribed at the moment of creation. The Sufi reads worship not as ritual performance alone but as the orientation of the entire being toward the Real. When all of life is worship, the distinction between sacred and mundane dissolves.',
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'e5ff63f9-75c2-47de-8bfd-e3ed84f82edc',
    surah_number: 52,
    arabic_name: 'At-Tur',
    english_name: 'The Mountain',
    revelation_type: 'meccan',
    core_theme: 'The oath-taking structure of divine speech and the certainty of divine recompense.',
    structural_axis: 'Divine Certainty',
    sufi_reflection: "God swears by the mountain, by the written parchment, by the frequented house, by the elevated canopy, by the swelling sea. Each oath invokes a created reality as witness to divine intention. The Sufi reads these as the divine signature embedded in nature: every elevated thing testifies to the Real whose elevation it reflects.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '8973b1b2-f430-4774-8de7-5c62f41bd99b',
    surah_number: 53,
    arabic_name: 'An-Najm',
    english_name: 'The Star',
    revelation_type: 'meccan',
    core_theme: 'Direct prophetic experience and the limits of human speculation about the divine.',
    structural_axis: 'Direct Revelation',
    sufi_reflection: "He does not speak from desire; it is nothing but a revelation revealed. This is the Sufi's model of authentic transmission: speech that originates not in the speaker's ego but in the divine reality that moves through the purified vessel. The practitioner who has refined the self approaches the quality of reception that makes genuine spiritual transmission possible.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '73ebce5a-376e-49f6-b7a5-589e85c177db',
    surah_number: 54,
    arabic_name: 'Al-Qamar',
    english_name: 'The Moon',
    revelation_type: 'meccan',
    core_theme: "The split moon as a sign and the repeated refrain of divine simplification of remembrance.",
    structural_axis: 'Divine Signs',
    sufi_reflection: "We have made the Qur'an easy for remembrance — is there anyone who will remember? This refrain, repeated four times, is an open invitation rather than a rhetorical challenge. The divine has removed the barriers to access. What remains is human willingness. The Sufi knows that the path is not hidden; it is simply seldom chosen with full commitment.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '63ac0596-e23f-4c51-900f-76a7fc9d0998',
    surah_number: 55,
    arabic_name: 'Ar-Rahman',
    english_name: 'The Most Merciful',
    revelation_type: 'medinan',
    core_theme: 'The comprehensive mercy of God encompassing all created beings across both worlds.',
    structural_axis: 'Divine Mercy',
    sufi_reflection: "Which of your Lord's favors will you deny? This refrain, repeated thirty-one times, is not accusation but invitation to awareness. The Sufi holds this Surah as the most complete enumeration of divine generosity. Every breath, every capacity, every dimension of existence is a gift unrequested and unearned. Gratitude is the appropriate response to a generosity this total.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'eac194bf-ed95-4cfd-8f9c-5768cc783da9',
    surah_number: 56,
    arabic_name: "Al-Waqi'ah",
    english_name: 'The Inevitable Event',
    revelation_type: 'meccan',
    core_theme: 'The three categories of souls and the certainty of the next world.',
    structural_axis: 'Eschatological Reality',
    sufi_reflection: "The souls are sorted into three: the foremost, the people of the right hand, and the people of the left hand. The Sufi reads this not only as future sorting but as present reality: the quality of one's orientation now determines one's station. The foremost are those who, in this life, have placed the Real before all else — not merely in belief but in the actual ordering of their existence.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '9af0abfa-fec4-4665-95c5-7352d0f62369',
    surah_number: 57,
    arabic_name: 'Al-Hadid',
    english_name: 'The Iron',
    revelation_type: 'medinan',
    core_theme: 'All sovereignty belongs to God and the proper relationship to worldly resources.',
    structural_axis: 'Divine Sovereignty and Non-Attachment',
    sufi_reflection: "Know that the life of this world is but amusement and diversion. This is not nihilism — the Surah also commands giving from what God has made you inheritors of. The world is real; it is simply not ultimate. The practitioner engages fully with material life while maintaining the inner recognition of its transience. Full presence with non-attachment.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'c5f4eb25-9a90-4f12-92f3-4b53e3921e10',
    surah_number: 58,
    arabic_name: 'Al-Mujadila',
    english_name: 'The Pleading Woman',
    revelation_type: 'medinan',
    core_theme: 'Divine responsiveness to individual petition and the ethics of gatherings.',
    structural_axis: 'Divine Responsiveness',
    sufi_reflection: "God has heard the woman who pleaded. The Surah opens with acknowledgment that the divine hears the specific plea of the individual — no cry is lost in the vastness of existence. This is among the most intimate openings in the Qur'an. The practitioner's specific prayer is not dissolved into a general divine awareness; it is specifically received.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'bb3b3051-30b6-47d2-8237-8ae972b05312',
    surah_number: 59,
    arabic_name: 'Al-Hashr',
    english_name: 'The Exile',
    revelation_type: 'medinan',
    core_theme: 'Divine power to remove that which has served its purpose and the attributes of God as the resolution of all human categories.',
    structural_axis: 'Divine Attributes',
    sufi_reflection: "This Surah concludes with one of the most concentrated sequences of divine names in the Qur'an: the Hidden and the Manifest, the Subtle and the Aware, the Sovereign, the Holy, the Giver of Peace. The Sufi reads this as the proper ending of any theological inquiry: categories dissolve into the reality of the living divine presence.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'eff7c0db-7bae-4317-8c91-6dae822c0c77',
    surah_number: 60,
    arabic_name: 'Al-Mumtahanah',
    english_name: 'The Woman to be Examined',
    revelation_type: 'medinan',
    core_theme: 'The ethics of alliances and the integrity of covenantal relationships.',
    structural_axis: 'Covenantal Integrity',
    sufi_reflection: "The Surah navigates the complex question of relationships across lines of belief — it prohibits alliance with active enemies of faith while affirming that God does not prohibit kindness and just dealings with those who do not fight against believers. The Sufi principle: distinctions are real, but they do not authorize cruelty. Justice applies universally.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '1615fd18-b771-4f69-a6d6-16c704295218',
    surah_number: 61,
    arabic_name: 'As-Saf',
    english_name: 'The Ranks',
    revelation_type: 'medinan',
    core_theme: 'Integrity between what is said and what is done, and divine love for those who act in unified ranks.',
    structural_axis: 'Integrity of Word and Action',
    sufi_reflection: "God loves those who fight in His cause in a rank as though they are a single solid structure. The Sufi reads this image as the integrated soul: thought, word, and action forming a coherent rank, moving in unified direction. The disintegrated self — whose speech contradicts its action, whose action contradicts its intention — has no such beauty.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '235fc55f-8bf8-42d6-98d0-0dfed21a0bc0',
    surah_number: 62,
    arabic_name: "Al-Jumu'ah",
    english_name: 'The Friday',
    revelation_type: 'medinan',
    core_theme: 'The communal gathering as the weekly renewal of collective spiritual orientation.',
    structural_axis: 'Communal Renewal',
    sufi_reflection: "The Friday prayer is more than congregation; it is the communal enactment of a principle: that individual spiritual development requires periodic collective reinforcement. The Sufi path is not only an inner journey but is walked in community. The weekly gathering is the institution that prevents the inner life from becoming purely privatized.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '262496df-36f4-4d9e-8f31-74432c566c0b',
    surah_number: 63,
    arabic_name: 'Al-Munafiqun',
    english_name: 'The Hypocrites',
    revelation_type: 'medinan',
    core_theme: 'The danger of misalignment between outward profession and inward reality.',
    structural_axis: 'Sincerity and Integration',
    sufi_reflection: "Hypocrisy is the precise inverse of the integrated soul. The hypocrite maintains outward form while the interior has departed. The Sufi tradition treats this not as a category of people to be condemned but as a tendency to be vigilantly monitored within oneself. The question is not whether others are hypocrites; it is whether one's own actions and intentions are aligned.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'f94bf4c7-e9b4-4024-a0ef-b09f015c22d2',
    surah_number: 64,
    arabic_name: 'At-Taghabun',
    english_name: 'The Mutual Disillusion',
    revelation_type: 'medinan',
    core_theme: 'The clarification of the real account on the Day of Judgment and the proper management of worldly attachments.',
    structural_axis: 'Detachment and Trust',
    sufi_reflection: "Your wealth and your children are but a trial. This is not a command to abandon family and wealth but a reminder of proper ordering. The Sufi does not flee relationship — the Sufi holds relationship within the larger container of divine trust. Everything held loosely can be given back. Everything grasped tightly becomes a source of suffering.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '93d842bf-1532-4587-8d18-7715cf8c9215',
    surah_number: 65,
    arabic_name: 'At-Talaq',
    english_name: 'The Divorce',
    revelation_type: 'medinan',
    core_theme: 'Divine mercy within the structure of law and the importance of God-consciousness in mundane affairs.',
    structural_axis: 'Divine Presence in the Mundane',
    sufi_reflection: "The Surah legislates the details of divorce — and within this least romantic of subjects inserts: whoever is conscious of God, He will make for him a way out and will provide for him from where he does not expect. The divine is present in the most difficult human situations. Taqwa — God-consciousness — is not reserved for elevated spiritual states; it is the orientation that navigates ordinary difficulty.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '4568f89a-fbaa-42f2-9e31-309adcde53a9',
    surah_number: 66,
    arabic_name: 'At-Tahrim',
    english_name: 'The Prohibition',
    revelation_type: 'medinan',
    core_theme: 'The prophetic household as a school of character and the necessity of sincere repentance.',
    structural_axis: 'Household as Spiritual School',
    sufi_reflection: "O you who believe, protect yourselves and your families from a fire. The household is not merely a social unit; it is a field of spiritual development. The Sufi principle: the relationships closest to us are our most demanding teachers. Those who practice inner development in retreat but cannot maintain it in the kitchen have not yet fully integrated what they have received.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '03a81f01-95b8-4ed2-8edf-cf557be43cf8',
    surah_number: 67,
    arabic_name: 'Al-Mulk',
    english_name: 'The Sovereignty',
    revelation_type: 'meccan',
    core_theme: 'Divine sovereignty over life and death and the signs of divine power in the natural order.',
    structural_axis: 'Divine Sovereignty',
    sufi_reflection: "Blessed is He in whose hand is dominion, and He is over all things competent — who created death and life to test you. Death is created before life in this verse — a subtle indication that the framework of mortality is part of the design, not an aberration. The Sufi lives in awareness of mortality not as morbidity but as the sharpener of genuine presence.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '099ed132-009c-412d-a72e-375014b65404',
    surah_number: 68,
    arabic_name: 'Al-Qalam',
    english_name: 'The Pen',
    revelation_type: 'meccan',
    core_theme: 'The defense of prophetic character and the dignity of those who endure slander with patience.',
    structural_axis: 'Character and Endurance',
    sufi_reflection: "You are upon an exalted character — addressed to the Prophet in the face of accusations of madness. The Sufi principle: the realized being will always be incomprehensible to the unrealized. This incomprehension typically takes the form of dismissal or pathologization. The appropriate response is not argument but continued embodiment of what one knows to be true.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '31551033-ad8f-4ecd-b9f8-f950d4c0ee09',
    surah_number: 69,
    arabic_name: 'Al-Haqqah',
    english_name: 'The Inevitable Reality',
    revelation_type: 'meccan',
    core_theme: 'The irresistible reality of the Day of Judgment and the fate of those who denied it.',
    structural_axis: 'Inevitable Reckoning',
    sufi_reflection: "Al-Haqqah — the Real, the Inevitable, the Truth — is one of the Qur'an's most confrontational Surahs. It strips away the comforting idea that consequences can be indefinitely deferred. The Sufi does not wait for the Day of Judgment to encounter reality; the practice of self-accounting brings the reckoning into the present, where it can still be responded to.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '1fd0bdce-aca0-468f-8bc3-5648578255b1',
    surah_number: 70,
    arabic_name: "Al-Ma'arij",
    english_name: 'The Ascending Stairways',
    revelation_type: 'meccan',
    core_theme: 'The ascending stairways to the divine and the qualities of the soul that ascend.',
    structural_axis: 'Spiritual Ascent',
    sufi_reflection: "The stairways ascending toward God. The Sufi path is precisely this — a structured ascent through stations of the soul toward the divine reality. The Surah also describes the qualities of the ascending soul: patient in calamity, consistent in prayer, recognizing the rights of the needy in their wealth. Ascent is not away from the world; it is through it.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '454059da-4301-4046-8a5e-24af13449ac6',
    surah_number: 71,
    arabic_name: 'Nuh',
    english_name: 'Noah',
    revelation_type: 'meccan',
    core_theme: 'The prophetic mission of patient invitation and the consequence of total rejection.',
    structural_axis: 'Patience in Prophetic Mission',
    sufi_reflection: "Noah called his people for 950 years. This duration is not incidental — it establishes that the divine does not abandon the mission because of slow response. The Sufi practitioner who finds progress slow does not abandon the path; they persist with the patience of Noah, trusting that sincere sustained effort is itself the fulfillment of the mission.",
    interfaith_resonance: 'Noah as shared patriarch of all Abrahamic traditions; the flood narrative cross-traditional.',
    has_interfaith_note: true,
  },
  {
    id: '78bbedb8-0209-4a97-b4c9-042d2147831e',
    surah_number: 72,
    arabic_name: 'Al-Jinn',
    english_name: 'The Jinn',
    revelation_type: 'meccan',
    core_theme: 'The invisible realm\'s recognition of divine truth and the universality of the prophetic message.',
    structural_axis: 'Universal Prophetic Message',
    sufi_reflection: "The jinn — invisible beings — heard the Qur'an, believed, and became transmitters. The divine message is not restricted to the visible human community; it addresses all of conscious existence. The Sufi reads this as confirmation that the inner world is populated with more than the ego. There are dimensions of the self that receive guidance before the conscious mind has processed it.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '10de17ef-1aca-45e3-b2e1-d110ada38a78',
    surah_number: 73,
    arabic_name: 'Al-Muzzammil',
    english_name: 'The Enwrapped',
    revelation_type: 'meccan',
    core_theme: 'Night vigil as the foundation of prophetic strength and the training ground for divine proximity.',
    structural_axis: 'Night Vigil and Preparation',
    sufi_reflection: "The Prophet is commanded to rise at night, recite slowly and deliberately, and prepare himself for a weighty word. The night vigil is not asceticism for its own sake; it is the clearing of internal space. When the ordinary noise of daily life is silenced, the subtle can be heard. The Sufi's tahajjud is not duty; it is the appointment kept.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '912cfbe0-0d67-4058-ba82-cccd288bd2de',
    surah_number: 74,
    arabic_name: 'Al-Muddaththir',
    english_name: 'The Cloaked One',
    revelation_type: 'meccan',
    core_theme: 'The beginning of the outward prophetic mission and the accountability of those who deny clear signs.',
    structural_axis: 'Prophetic Commissioning',
    sufi_reflection: "Arise and warn. The retreat ends; the mission begins. The Sufi who has completed an inner preparation phase eventually receives a summons to outward engagement. Withdrawal is not the final state; it is the preparation for genuine contribution. The cloaked figure rises and speaks.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'bff659a2-ef7c-4e2f-80aa-05d5d8bbf18b',
    surah_number: 75,
    arabic_name: 'Al-Qiyamah',
    english_name: 'The Resurrection',
    revelation_type: 'meccan',
    core_theme: "The certainty of resurrection and the human soul's own testimony against itself.",
    structural_axis: 'Self-Accountability',
    sufi_reflection: "Nay, the human being is evidence against himself. The soul knows its own reality — its pretenses, its evasions, its actual intentions beneath the stated ones. The Day of Judgment does not introduce new information; it reveals what was already known. Self-accounting in the present is simply this judgment brought forward into the time when it can still effect change.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '5ca41980-4e31-4bfd-a51b-1172d92a2e19',
    surah_number: 76,
    arabic_name: 'Al-Insan',
    english_name: 'The Human Being',
    revelation_type: 'medinan',
    core_theme: "The human being's journey from nothingness to accountability and the reward of the righteous.",
    structural_axis: 'Human Dignity and Gratitude',
    sufi_reflection: "Was there not a time when the human being was a thing not mentioned? This opening dismantles the ego's grandiosity: existence is a gift, not an entitlement. The Sufi holds this recognition as the beginning of genuine humility — not self-deprecation but accurate ontology. I was nothing; I am given existence; I will return. Gratitude is the correct response to the middle term.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'e5920302-2b26-4acf-8de7-c4b2da174537',
    surah_number: 77,
    arabic_name: 'Al-Mursalat',
    english_name: 'Those Sent Forth',
    revelation_type: 'meccan',
    core_theme: 'The divine agents sent in service of the divine will and the repeated refrain of woe to deniers.',
    structural_axis: 'Divine Agency',
    sufi_reflection: "The Surah employs natural forces — winds, scatterers, spreaders, separators, deliverers — as images of divine agency operating through the created order. The Sufi reads creation as populated with divine agents. Nothing is merely natural in the mechanical sense; everything is a vehicle of divine action. Seeing the world this way is itself a form of worship.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '4c385dbd-0ae7-492a-b55e-8d637e09abac',
    surah_number: 78,
    arabic_name: "An-Naba'",
    english_name: 'The Great News',
    revelation_type: 'meccan',
    core_theme: 'The certainty of the great news — the resurrection — and the comprehensive provision of the next world.',
    structural_axis: 'Certainty of the Next World',
    sufi_reflection: "What are they asking one another about — the great news about which they differ? The Surah does not dramatize its subject; it asserts it with confidence. The Sufi's certainty about the next world is not based on argument but on the inner recognition that this world's transience points necessarily to something permanent. The great news is already encoded in the nature of existence.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'c9ee46ea-17dd-45ba-a37a-f7cccb52534a',
    surah_number: 79,
    arabic_name: "An-Nazi'at",
    english_name: 'Those Who Extract',
    revelation_type: 'meccan',
    core_theme: 'The angels who extract souls at death and the story of Moses as reminder of divine power.',
    structural_axis: 'Divine Power over Life and Death',
    sufi_reflection: "The extracting angels — those who pull the soul from the body at death — are a vivid image of the soul's complete dependence on the divine. The Sufi does not fear death as annihilation but holds it as the final act of divine care: the same care that breathed existence into the soul ultimately receives it back. Death is not the opposite of life; it is its completion.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '9c01eb02-d4b5-4122-9023-56b44b456909',
    surah_number: 80,
    arabic_name: 'Abasa',
    english_name: 'He Frowned',
    revelation_type: 'meccan',
    core_theme: 'Divine rebuke of the Prophet for his momentary prioritization of the powerful over the sincere seeker.',
    structural_axis: 'Accessibility of Guidance',
    sufi_reflection: "The Prophet frowned at the blind man who interrupted his address to the powerful of Quraysh. God rebukes him. This is among the most remarkable passages in the Qur'an: divine correction of prophetic conduct in favor of a sincere seeker over a prestigious doubter. The Sufi principle: sincere seeking outweighs social position in the economy of divine attention. The blind man's sincerity mattered more than the leaders' credentials.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '97adf4c6-cea0-41c3-9e1e-eb3f6275cffb',
    surah_number: 81,
    arabic_name: 'At-Takwir',
    english_name: 'The Folding Up',
    revelation_type: 'meccan',
    core_theme: 'The unfolding of cosmic dissolution and the protection of divine guidance for sincere seekers.',
    structural_axis: 'Cosmic Dissolution',
    sufi_reflection: "When the sun is folded up, when the stars fall, when the mountains are set in motion — the entire created order is impermanent. The Sufi holds the vivid imagery of cosmic dissolution not as threat but as liberation: attachment to the permanent is wisdom; attachment to the transient is error. This world's dissolution reveals what was always permanent beneath it.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '4d633e8d-2a1e-40fe-b742-999033707a27',
    surah_number: 82,
    arabic_name: 'Al-Infitar',
    english_name: 'The Cleaving',
    revelation_type: 'meccan',
    core_theme: "The dissolution of the sky and the divine awareness of every soul's actions.",
    structural_axis: 'Divine Awareness',
    sufi_reflection: "What has deceived you concerning your Lord, the Generous? This challenge — not angry but almost tender in its phrasing — is the Surah's heart. The divine question is not rhetorical accusation but genuine inquiry into the mechanism of the soul's self-deception. What, precisely, convinced you that the generous reality could be ignored? The Sufi asks this question of themselves continuously.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'bb8d7e6f-7fee-4bef-9fa0-c370de0b84b8',
    surah_number: 83,
    arabic_name: 'Al-Mutaffifin',
    english_name: 'The Defrauders',
    revelation_type: 'meccan',
    core_theme: 'The ethics of just measure and the register of the righteous.',
    structural_axis: 'Justice in Exchange',
    sufi_reflection: "Those who defraud in measure are condemned; those who give full measure to others but demand it in full for themselves embody structural injustice. The Sufi reads this as an inner principle: the soul that demands full recognition for its own states while granting minimal acknowledgment to others is engaged in spiritual fraud. Justice begins in the interior accounting.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '005852ac-acfb-421a-a3ed-23fc6996068a',
    surah_number: 84,
    arabic_name: 'Al-Inshiqaq',
    english_name: 'The Splitting Open',
    revelation_type: 'meccan',
    core_theme: "The earth splitting open before its Lord and the human being's journey toward the divine meeting.",
    structural_axis: 'Meeting with the Divine',
    sufi_reflection: "O human being, you are laboring toward your Lord with great effort and you will meet Him. The labor is real; the meeting is certain. The Sufi holds this verse as the destination of the entire inner path: the meeting with the Real that is the telos of all genuine practice. Everything prior is preparation; this is the purpose.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'a201ff57-1621-4488-8d40-a9277ff492c2',
    surah_number: 85,
    arabic_name: 'Al-Buruj',
    english_name: 'The Mansions of the Stars',
    revelation_type: 'meccan',
    core_theme: 'The cosmic witness and the stories of those who were persecuted for their faith.',
    structural_axis: 'Witnessing and Constancy',
    sufi_reflection: "The celestial mansions witness the trial of the believers. The entire cosmos observes and records. The Sufi principle: nothing genuine passes unwitnessed. The one who maintains integrity under pressure — even when no human witness is present — is witnessed by a much larger audience. Constancy in the unseen is the quality that develops authentic interior structure.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '0d564e4d-aa42-4cb9-b10e-460df77df0dc',
    surah_number: 86,
    arabic_name: 'At-Tariq',
    english_name: 'The Piercing Star',
    revelation_type: 'meccan',
    core_theme: 'The piercing star as a sign of divine vigilance and the power of the divine word.',
    structural_axis: 'Divine Vigilance',
    sufi_reflection: "Every soul has an appointed guardian — not as surveillance but as divine care accompanying each existence. The Sufi reads the piercing star as an image of divine attention that penetrates all opacity. Nothing in the inner life is obscured from this attention. The practice of being fully seen, without concealment, is itself a discipline of liberation.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '90540890-f03b-4329-9a12-130111396a87',
    surah_number: 87,
    arabic_name: "Al-A'la",
    english_name: 'The Most High',
    revelation_type: 'meccan',
    core_theme: 'The divine instruction to glorify the Most High and the ease of the divinely facilitated path.',
    structural_axis: 'Glorification and Ease',
    sufi_reflection: "We will ease you toward ease. The path of those aligned with the divine is not made difficult by the divine. The difficulty arises from the ego's resistance, not from the nature of the path itself. The Sufi who has reduced the ego's resistance discovers that what appeared arduous becomes natural, and what appeared natural to the ego becomes recognizably burdensome.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '857b55c8-4a49-4a84-b810-fba83c150794',
    surah_number: 88,
    arabic_name: 'Al-Ghashiyah',
    english_name: 'The Overwhelming',
    revelation_type: 'meccan',
    core_theme: 'The overwhelming event of the Day of Judgment and the signs of divine power in creation.',
    structural_axis: 'Overwhelming Reality',
    sufi_reflection: "Do they not look at the camels — how they were created? The most ordinary things are extraordinary when perceived properly. The Sufi cultivation of wonder — the ability to see the miraculous in the mundane — is a spiritual achievement, not a regression to naivety. The camel, the sky, the mountains, the earth: each is a sign that instructs the attentive.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '505b2b27-e454-453e-ad95-4f2943c200d6',
    surah_number: 89,
    arabic_name: 'Al-Fajr',
    english_name: 'The Dawn',
    revelation_type: 'meccan',
    core_theme: 'The divine oath by time and the story of civilizations destroyed by their own arrogance.',
    structural_axis: 'Divine Oath and Historical Accountability',
    sufi_reflection: "By the dawn, by the ten nights — God swears by time's most liminal moments. The Sufi pays particular attention to the transitional times: dawn, dusk, the threshold between states. These are moments when the veil between the ordinary and the extraordinary thins. Regular practice at these transitions is not superstition but the cultivation of perceptual sensitivity.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '68ca2eb1-77d3-48d3-a14c-5e398e23c9f5',
    surah_number: 90,
    arabic_name: 'Al-Balad',
    english_name: 'The City',
    revelation_type: 'meccan',
    core_theme: 'The exertion required for the steep path and the freeing of the captive as highest good.',
    structural_axis: 'Liberation of the Vulnerable',
    sufi_reflection: "The steep path — freeing a neck, feeding an orphan, feeding the destitute in distress — is demanding because it runs counter to the ego's natural tendency toward self-preservation and accumulation. The Sufi path is precisely this countercultural exertion: the practices that liberate others gradually liberate the practitioner from the very ego that resisted liberation.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '28ddf5bb-2e73-43df-b412-ae3caefbc8f0',
    surah_number: 91,
    arabic_name: 'Ash-Shams',
    english_name: 'The Sun',
    revelation_type: 'meccan',
    core_theme: 'The soul and its purification as the central concern of human existence.',
    structural_axis: 'Soul Purification',
    sufi_reflection: "By the soul and He who proportioned it and inspired it with its wickedness and its righteousness — the one who purifies it has succeeded; the one who corrupts it has failed. The Sufi holds this as the clearest statement of the path's purpose. Everything else — practice, study, community, guidance — exists in service of this single project: the purification and elevation of the soul.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'ab9e2f50-283a-49cf-98bf-07cc9aa0e9aa',
    surah_number: 92,
    arabic_name: 'Al-Layl',
    english_name: 'The Night',
    revelation_type: 'meccan',
    core_theme: 'The two paths — giving and withholding — and the divine facilitation of each.',
    structural_axis: 'Two Paths',
    sufi_reflection: "The Surah presents a binary: the one who gives, is conscious of God, and affirms the good — God eases them toward ease. The one who withholds, considers themselves self-sufficient, and denies the good — God eases them toward hardship. The Sufi does not experience this as threat but as the natural logic of alignment. The soul that contracts around itself becomes harder to move. The soul that opens becomes responsive to divine guidance.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '3b5ad989-1633-4f1b-9b1d-3b5d7acc7007',
    surah_number: 93,
    arabic_name: 'Ad-Duha',
    english_name: 'The Morning Brightness',
    revelation_type: 'meccan',
    core_theme: 'Divine reassurance to the Prophet in a moment of perceived abandonment.',
    structural_axis: 'Divine Constancy',
    sufi_reflection: "Your Lord has not abandoned you, nor has He detested you. This Surah was revealed in a period when revelation had paused and the Prophet feared divine withdrawal. The reassurance is intimate and specific: the One who found you lost and guided you has not withdrawn. The Sufi holds this as the foundation of hope: no genuine seeker, no matter how dark the interior season, has been abandoned by the Real.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'a6b989ea-b351-43c3-b13d-ab20cecfcfee',
    surah_number: 94,
    arabic_name: 'Ash-Sharh',
    english_name: 'The Relief',
    revelation_type: 'meccan',
    core_theme: 'The expansion of the prophetic chest and the principle that hardship is followed by ease.',
    structural_axis: 'Relief after Hardship',
    sufi_reflection: "With hardship comes ease — stated twice. The Sufi reads this not as consolation but as structural principle: the very hardship that compresses the soul is the mechanism that creates the capacity for greater expansion. The contracted state is not a problem to be solved; it is a stage to be passed through. After every genuine compression, a more expansive opening becomes possible.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '371e0f2b-d3eb-48e5-ba77-65861608aaac',
    surah_number: 95,
    arabic_name: 'At-Tin',
    english_name: 'The Fig',
    revelation_type: 'meccan',
    core_theme: 'The human being created in the best of forms and the consequences of returning to lowest state.',
    structural_axis: 'Human Dignity and Responsibility',
    sufi_reflection: "We have created the human being in the best of forms. The Sufi holds this verse against all self-deprecation that masquerades as humility. The original form — the primordial dignity of the human — is the starting point, not a destination. Spiritual practice is not the acquisition of a new dignity but the recovery of the original one that was obscured by forgetting.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '257d8e9f-8b66-41f9-983c-aa01c6ee178f',
    surah_number: 96,
    arabic_name: 'Al-Alaq',
    english_name: 'The Clot',
    revelation_type: 'meccan',
    core_theme: 'The first revelation — Read — and the divine origination of human knowledge.',
    structural_axis: 'Knowledge and Origin',
    sufi_reflection: "Read in the name of your Lord who created. The first word of revelation is an invitation to knowledge — but knowledge grounded in divine origination, not autonomous human reason. The Sufi holds that all genuine knowledge is, at its root, a remembering of what the soul already knows from its proximity to the Real before embodiment. Learning is the recovery of forgotten origin.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'b25cb261-69e6-4213-ac68-6ebe16eb56f8',
    surah_number: 97,
    arabic_name: 'Al-Qadr',
    english_name: 'The Power',
    revelation_type: 'meccan',
    core_theme: "The Night of Power — better than a thousand months — and the descent of the angels and the Spirit.",
    structural_axis: 'Sacred Time',
    sufi_reflection: "The Night of Power — laylat al-qadr — is the most sacred night of the year, the moment of the Qur'an's first descent. The Sufi holds that certain moments carry more spiritual density than others — that time is not homogeneous. The practitioner learns to recognize and fully inhabit the sacred intervals: the pre-dawn hour, the pause between breaths, the moment before sleep. These are the night of power in miniature.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '0ece9261-cfa5-45c9-9141-c8ec455fac34',
    surah_number: 98,
    arabic_name: 'Al-Bayyinah',
    english_name: 'The Clear Proof',
    revelation_type: 'meccan',
    core_theme: 'The clear proof of divine guidance and the distinction between those who accept and those who reject.',
    structural_axis: 'Clarity of Guidance',
    sufi_reflection: "The religion of pure sincerity — din al-qayyimah — is the phrase the Sufi treasures from this Surah. Religion is not primarily external observance but internal orientation. Pure sincerity cannot be performed; it can only be cultivated. All external form is the scaffolding in service of this interior quality. When sincerity is complete, the scaffolding has served its purpose.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'fdfd6b14-5e2e-4701-8a4c-4a43ca26c2ba',
    surah_number: 99,
    arabic_name: 'Az-Zalzalah',
    english_name: 'The Earthquake',
    revelation_type: 'meccan',
    core_theme: "The earth's total disclosure of its contents and the individual accounting of every atom's weight.",
    structural_axis: 'Total Accountability',
    sufi_reflection: "Whoever does an atom's weight of good will see it; whoever does an atom's weight of evil will see it. The Sufi holds this as the principle of absolute spiritual precision: nothing is without consequence, nothing is without record. This is not oppressive accounting but liberating precision — every genuine act of goodness, however small and unwitnessed, is permanently registered.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'e19455dc-3fed-4ea0-a333-ec78301e75eb',
    surah_number: 100,
    arabic_name: 'Al-Adiyat',
    english_name: 'The Charging Steeds',
    revelation_type: 'meccan',
    core_theme: 'The ungrateful human nature and the divine awareness of what the heart conceals.',
    structural_axis: 'Human Nature and Gratitude',
    sufi_reflection: "The human being is intensely ungrateful to his Lord. This is not condemnation but diagnosis. The default condition of the unreflective soul is ingratitude — taking existence, health, provision, and relationship for granted. The Sufi path is partly the cultivation of radical gratitude: the sustained recognition that everything received was not owed.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '3b6c8749-adcc-4a03-ae32-43bb9c7c7ae5',
    surah_number: 101,
    arabic_name: "Al-Qari'ah",
    english_name: 'The Striking Calamity',
    revelation_type: 'meccan',
    core_theme: 'The striking calamity of the Day of Judgment and the weighing of deeds.',
    structural_axis: 'Moral Weight',
    sufi_reflection: "Whose scales are heavy with good — he is in a pleasing life. Whose scales are light — his refuge is the abyss. The Sufi does not wait for the weighing; daily self-accounting is the practitioner's version of this scale. The question is not what the scale will reveal at the end but what the honest interior assessment reveals now, while there is still capacity to add to the weight.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'd7f18eb6-5b7a-46ca-9f30-20ac23242d9a',
    surah_number: 102,
    arabic_name: 'At-Takathur',
    english_name: 'The Competition for More',
    revelation_type: 'meccan',
    core_theme: 'The human obsession with accumulation and the visit to the graves as its correction.',
    structural_axis: 'Non-Attachment to Accumulation',
    sufi_reflection: "Competition in accumulation diverts you until you visit the graves. The Sufi sees in this short Surah a complete diagnosis of the contemporary condition: the soul distracted from its essential purpose by the competition for more — more wealth, more status, more recognition. The visit to the graves is not morbid; it is clarifying. Everything accumulated is left there.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '4495a3f8-0fea-46e6-a48f-4899414f4df3',
    surah_number: 103,
    arabic_name: 'Al-Asr',
    english_name: 'The Declining Day',
    revelation_type: 'meccan',
    core_theme: 'The human condition of loss and the four qualities that constitute genuine salvation.',
    structural_axis: 'Time and Genuine Action',
    sufi_reflection: "By time — the human is in loss. Except those who believe, do righteous deeds, enjoin truth upon one another, and enjoin patience upon one another. In three verses, the entire human situation is mapped: the default is loss; the alternative requires four qualities simultaneously — faith, action, truthful community, and patient support. The Sufi path cultivates all four, in that order.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'f7d6bcba-2da4-4742-afbc-3c3dd404e0a7',
    surah_number: 104,
    arabic_name: 'Al-Humazah',
    english_name: 'The Traducer',
    revelation_type: 'meccan',
    core_theme: 'The condemnation of slander, backbiting, and the delusion of wealth as protection.',
    structural_axis: "Ego's Defenses",
    sufi_reflection: "Woe to every scorner and mocker — who has gathered wealth and counted it, thinking his wealth will make him immortal. The Sufi reads in this Surah the anatomy of the defended ego: it attacks others to protect itself, it accumulates to secure itself, and it believes its accumulations confer permanence. All three are forms of the same error: the substitution of created supports for the Real.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'd2d6c54d-f491-4cb8-8536-978ba55cb61d',
    surah_number: 105,
    arabic_name: 'Al-Fil',
    english_name: 'The Elephant',
    revelation_type: 'meccan',
    core_theme: 'The destruction of the army of the elephant as a demonstration of divine protection of the sacred house.',
    structural_axis: 'Divine Protection',
    sufi_reflection: "The most powerful human military force of its time was destroyed by small birds carrying stones. The Sufi reads this as the principle that divine protection operates through what appears insignificant to ordinary perception. The practitioner who has aligned with the Real does not need the world's categories of power. Protection comes from its actual source, not from its appearance.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'fd0ef31f-5216-426c-a527-e394c60a6a3b',
    surah_number: 106,
    arabic_name: 'Quraysh',
    english_name: 'Quraysh',
    revelation_type: 'meccan',
    core_theme: 'The divine provision for the Quraysh and the requirement of worship in gratitude.',
    structural_axis: 'Gratitude for Provision',
    sufi_reflection: "God made the Quraysh's journeys safe and their provisions secure — so let them worship the Lord of this house. The logic is gratitude-as-worship: provision received creates the obligation of recognition. The Sufi reads this as the universal principle: existence itself, continuously received from the divine, continuously obligates the recognition that is worship. Gratitude is not optional; it is the appropriate response to ongoing gift.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'cabe0f77-b597-4e96-bae1-96f424143216',
    surah_number: 107,
    arabic_name: "Al-Ma'un",
    english_name: 'The Small Kindnesses',
    revelation_type: 'meccan',
    core_theme: 'The condemnation of those who perform religion while neglecting the orphan and the needy.',
    structural_axis: 'Social Responsibility as Faith',
    sufi_reflection: "Have you seen the one who denies the Day of Judgment? It is the one who drives away the orphan and does not encourage feeding the poor. The Sufi holds this as the most direct equation in the Qur'an: neglect of the vulnerable is functional denial of the divine judgment. Spiritual development that leaves social conscience undeveloped is not yet genuine. The prayer of the one who is heedless of the needy is a performance without substance.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: 'cf524216-8eac-4933-9b37-895c6d4987fa',
    surah_number: 108,
    arabic_name: 'Al-Kawthar',
    english_name: 'The Abundance',
    revelation_type: 'meccan',
    core_theme: 'The divine grant of abundance to the Prophet and the severing of those who hate him.',
    structural_axis: 'Divine Abundance',
    sufi_reflection: "We have given you the Kawthar — the river of abundance, of goodness, of overflowing divine gift. The shortest Surah in the Qur'an compresses the entire economy of divine generosity into three verses. The Sufi holds that the practitioner aligned with the Real has access to an inner kawthar — a spring of meaning, purpose, and vitality that the world cannot provide and cannot take away.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '7d8a423a-56f8-4705-9ffa-5d5396cbda66',
    surah_number: 109,
    arabic_name: 'Al-Kafirun',
    english_name: 'The Disbelievers',
    revelation_type: 'meccan',
    core_theme: 'The clear and respectful establishment of religious distinction and the principle of freedom of conviction.',
    structural_axis: 'Clarity of Distinction',
    sufi_reflection: "To you your religion; to me mine. The Sufi reads this not as dismissal but as respect. Genuine pluralism requires clear particularity: to blur the lines is not to honor the other but to dissolve what makes genuine encounter possible. The Sufi path does not pretend that all paths are identical; it holds its own distinctiveness with clarity while recognizing the sincere seeker within each tradition.",
    interfaith_resonance: 'A foundational text for Islamic approaches to religious pluralism and interfaith engagement.',
    has_interfaith_note: true,
  },
  {
    id: '5436d034-b426-4dc2-821f-7c83b04bd1e6',
    surah_number: 110,
    arabic_name: 'An-Nasr',
    english_name: 'The Divine Support',
    revelation_type: 'medinan',
    core_theme: 'Divine support, the completion of the prophetic mission, and the return to divine glorification.',
    structural_axis: 'Completion and Return',
    sufi_reflection: "When the divine support comes and the victory — enter into the religion in crowds — then glorify your Lord and ask His forgiveness. The Sufi reads the command to seek forgiveness at the moment of greatest worldly success as the deepest discipline: victory does not belong to the self. The correct response to achievement is not celebration of the ego's contribution but immediate return to the source of all support.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '286db026-0521-4d69-b8bd-10afa120af3d',
    surah_number: 111,
    arabic_name: 'Al-Masad',
    english_name: 'The Palm Fiber',
    revelation_type: 'meccan',
    core_theme: 'The futility of wealth and status in resisting divine truth.',
    structural_axis: 'Futility of Worldly Defense',
    sufi_reflection: "Abu Lahab's wealth and social standing could not protect him from divine decree. The Sufi principle: no accumulation of worldly advantage constitutes a genuine defense against the consequences of one's orientation. The soul that has aligned with the Real needs no such defense. The soul that has not possesses an illusion of safety that will not hold.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '259ba61a-a30c-4ea1-aa0d-b72acea7da26',
    surah_number: 112,
    arabic_name: 'Al-Ikhlas',
    english_name: 'The Sincerity',
    revelation_type: 'meccan',
    core_theme: "The absolute unity and self-sufficiency of God — the theological heart of the Qur'an.",
    structural_axis: 'Divine Unity',
    sufi_reflection: "God is One. God is Samad — the Eternally Self-Sufficient. He neither begets nor was begotten. And there is nothing comparable to Him. In four verses, all the conditions for genuine tawhid are established. The Sufi holds Al-Ikhlas as the entire path in miniature: the movement from multiplicity to unity, from dependence on created supports to alignment with the only truly Self-Sufficient reality.",
    interfaith_resonance: 'Engages directly with Christian Trinitarian theology and Jewish formulations of divine unity.',
    has_interfaith_note: true,
  },
  {
    id: 'b8b81965-cb07-45f3-bae5-aa963c5a0e53',
    surah_number: 113,
    arabic_name: 'Al-Falaq',
    english_name: 'The Daybreak',
    revelation_type: 'meccan',
    core_theme: "Seeking refuge in God from the harms of creation — the outer enemies of the soul.",
    structural_axis: 'Divine Protection from External Harm',
    sufi_reflection: "Say: I seek refuge in the Lord of daybreak — from the evil of what He created, from the evil of darkness when it settles, from the evil of those who blow on knots, from the evil of an envier when he envies. The Sufi reads this as the seeker's recognition that spiritual progress attracts opposition from forces that are real but not ultimate. Refuge is sought from the Source, not from another created power.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
  {
    id: '2e2b7310-4245-4599-bdad-fa38148dd211',
    surah_number: 114,
    arabic_name: 'An-Nas',
    english_name: 'Mankind',
    revelation_type: 'meccan',
    core_theme: "Seeking refuge in God from the inner enemy — the whisperer who retreats when God is remembered.",
    structural_axis: 'Divine Protection from the Whispering Ego',
    sufi_reflection: "The whisperer who whispers in the hearts of people — from among jinn and people. The Sufi holds this final Surah as the most intimate diagnosis: the primary enemy is not external but internal, and it is specifically a whisperer — subtle, insinuating, not announcing itself as opposition. This is the ego's mode: it does not argue frontally but whispers alternatives. The remedy is the same as the diagnosis: the remembrance of God that causes the whisper to retreat.",
    interfaith_resonance: null,
    has_interfaith_note: false,
  },
];

export function getSurahByNumber(number: number): SurahData | undefined {
  return SURAH_COMMENTARY.find((s) => s.surah_number === number);
}

export function getPrevSurah(number: number): Pick<SurahData, 'surah_number' | 'arabic_name' | 'english_name'> | null {
  if (number <= 1) return null;
  const s = getSurahByNumber(number - 1);
  return s ? { surah_number: s.surah_number, arabic_name: s.arabic_name, english_name: s.english_name } : null;
}

export function getNextSurah(number: number): Pick<SurahData, 'surah_number' | 'arabic_name' | 'english_name'> | null {
  if (number >= 114) return null;
  const s = getSurahByNumber(number + 1);
  return s ? { surah_number: s.surah_number, arabic_name: s.arabic_name, english_name: s.english_name } : null;
}
